VariantDir('out','src')

programs = [ {'name': 'linkedListTest'   , 'sources': ['linkedListTest']        , 'objects': []},
	     {'name': 'cookingAssitant'  , 'sources': ['main', 'recipe', 'step'], 'objects': []},
            ]

for program in programs:
    for source in program['sources']:
        program['objects'].extend(Object('out/%s.cpp' % source))
    prgm = Program(target = program['name'],
                   source = program['objects'])

