all: fib_decoding fib_coding 32bit_coding

clean:
	rm fib_coding fib_decoding 32bit_coding

fib_decoding: fibonacci_decoding.cpp
	g++ fibonacci_decoding.cpp -o fib_decoding

fib_coding: fibonacci_coding.cpp
	g++ fibonacci_coding.cpp -o fib_coding

32bit_coding: 32bit_coding.cpp
	g++ 32bit_coding.cpp -o 32bit_coding
