env = Environment()

env.Append(CPPPATH = ['mbedtls/include',
                      'utilities',
                     ])

sha256 = env.Object('mbedtls/library/sha256.c')
utils = env.Object('mbedtls/library/platform_util.c')

utilities = env.Object('utilities/utilities.c')

pow = env.Program(['pow/pow.c'] + sha256 + utils + utilities)
